CREATE TABLE LOGI 
(
LOG VARCHAR(128) NOT NULL
) TABLESPACE COURIER;

alter session set "_oracle_script"=true;

CREATE USER LOGGER
    IDENTIFIED BY log123
    DEFAULT TABLESPACE COURIER
    QUOTA 50M ON COURIER
    TEMPORARY TABLESPACE temp
    QUOTA 50M ON system;
    
GRANT CONNECT TO LOGGER;

GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.LOGI TO LOGGER;

