alter session set "_oracle_script"=true;

CREATE ROLE ServiceRole;
GRANT CREATE SESSION TO ServiceRole;
GRANT SELECT ON MAGAZYNY TO ServiceRole;
GRANT SELECT ON DANE_PROCOWNIKOW TO ServiceRole;
GRANT SELECT ON STANOWISKA TO ServiceRole;
GRANT SELECT , INSERT, DELETE, UPDATE ON KLIENCI TO ServiceRole;

CREATE USER FLAGA
    IDENTIFIED BY 123
    DEFAULT TABLESPACE COURIER
    QUOTA 10M ON COURIER
    TEMPORARY TABLESPACE temp
    QUOTA 5M ON system;

GRANT ServiceRole To FLAGA;

CREATE ROLE AdminRole;
GRANT CREATE SESSION TO AdminRole;
GRANT SELECT , INSERT, DELETE, UPDATE ON MAGAZYNY TO AdminRole;
GRANT SELECT , INSERT, DELETE, UPDATE ON DANE_PROCOWNIKOW TO AdminRole;
GRANT SELECT , INSERT, DELETE, UPDATE ON STANOWISKA TO AdminRole;
GRANT SELECT , INSERT, DELETE, UPDATE ON KLIENCI TO AdminRole;

CREATE USER FADM
    IDENTIFIED BY 123
    DEFAULT TABLESPACE COURIER
    QUOTA 50M ON COURIER
    TEMPORARY TABLESPACE temp
    QUOTA 50M ON system;

GRANT ROLE AdminRole To FLAGA;

