CREATE TABLESPACE COURIER DATAFILE 'courier.dat' SIZE 50M AUTOEXTEND ON;
CREATE SEQUENCE SEQ_MAGAZYNY_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STANOWISKA_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRACOWNICY_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_KLIENCI_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRZESYLKI_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DOSTAWCY_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE MAGAZYNY
(
  ID NUMBER DEFAULT SEQ_MAGAZYNY_ID.NEXTVAL PRIMARY KEY,
  NAZWA VARCHAR(32) NOT NULL,
  ADRES VARCHAR(128)
)
TABLESPACE COURIER;

INSERT INTO MAGAZYNY (NAZWA,ADRES)
VALUES
('Wroclaw','Wroclaw Kurierska 12');
INSERT INTO MAGAZYNY (NAZWA,ADRES)
VALUES
('Jelenia Gora','Jelenia Gora Magazynowa 3');

CREATE TABLE STANOWISKA
(
  ID NUMBER DEFAULT SEQ_STANOWISKA_ID.NEXTVAL PRIMARY KEY,
  NAZWA VARCHAR(32) NOT NULL
)
TABLESPACE COURIER;

INSERT INTO STANOWISKA (NAZWA)
VALUES ('Admin');
INSERT INTO STANOWISKA (NAZWA)
VALUES ('Dyrektor');
INSERT INTO STANOWISKA (NAZWA)
VALUES ('Obsluga Zlecen');
INSERT INTO STANOWISKA (NAZWA)
VALUES ('Dostawca');
INSERT INTO STANOWISKA (NAZWA)
VALUES ('Magazynier');

CREATE TABLE DANE_PROCOWNIKOW
(
  ID NUMBER DEFAULT SEQ_PRACOWNICY_ID.NEXTVAL PRIMARY KEY,
  IMIE VARCHAR(32) NOT NULL,
  NAZWISKO VARCHAR(32) NOT NULL,
  ADRES VARCHAR(128),
  STANOWISKO NUMBER CONSTRAINT DP_STANOWISKO_FK REFERENCES STANOWISKA(ID),
  MAGAZYN NUMBER CONSTRAINT DP_MAGAZYN_FK REFERENCES MAGAZYNY(ID)
)
TABLESPACE COURIER;

INSERT INTO DANE_PRACOWNIKOW (IMIE,NAZWISKO,STANOWISKO,MAGAZYN)
VALUES ('Kamil','Flaga',1,1);
INSERT INTO DANE_PRACOWNIKOW (IMIE,NAZWISKO,STANOWISKO,MAGAZYN)
VALUES ('Benio','Benski',4,1);
INSERT INTO DANE_PRACOWNIKOW (IMIE,NAZWISKO,STANOWISKO,MAGAZYN)
VALUES ('Rafczak','Rafczacki',3,2);
INSERT INTO DANE_PRACOWNIKOW (IMIE,NAZWISKO,STANOWISKO,MAGAZYN)
VALUES ('Jan','Kowalski',5,2);

CREATE TABLE KLIENCI
(
  ID NUMBER DEFAULT SEQ_KLIENCI_ID.NEXTVAL PRIMARY KEY,
  IMIE VARCHAR(32) NOT NULL,
  NAZWISKO VARCHAR(32) NOT NULL,
  ADRES VARCHAR(128),
  TYP_KLIENTA VARCHAR(12),
  CONSTRAINT klienciTyp CHECK(TYP_KLIENTA IN ('odbiorca', 'nadawca')),
  MAGAZYN NUMBER CONSTRAINT KL_MAGAZYN_FK REFERENCES MAGAZYNY(ID)
)
TABLESPACE COURIER;

INSERT INTO KLIENCI (IMIE,NAZWISKO,TYP_KLIENTA,MAGAZYN)
VALUES ('Adam','Piechota','odbiorca',1);
INSERT INTO KLIENCI (IMIE,NAZWISKO,TYP_KLIENTA,MAGAZYN)
VALUES ('Benio','Zmotoryzowany','odbiorca',2);
INSERT INTO KLIENCI (IMIE,NAZWISKO,TYP_KLIENTA,MAGAZYN)
VALUES ('Kamil','Rowerem','nadawca',1);
INSERT INTO KLIENCI (IMIE,NAZWISKO,TYP_KLIENTA,MAGAZYN)
VALUES ('Filip','Nadawczyk','nadawca',2);